/* generated by /host/tools/elfloader-tool/../cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 1;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[1] = {
	{ .start = 2149580800, .end = 5368709120 },
};
/* generated by /host/tools/elfloader-tool/../cmake-tool/helpers/platform_sift.py END */
