IMAGE_ELF: false
IMAGE_BINARY: false
ELFLOADER_IMAGE: "elf"
IMAGE_ELF: true # ElfloaderImageELF=ON
ARM_MONITOR_HOOK: false
GPT_PTIMER_NS_PL1_ACCESS: false
ARM_ERRATA_764369: false
HASH_NONE: false
HASH_SHA: false
HASH_MD5: false
HASH_INSTRUCTIONS: "hash_none"
HASH_NONE: true # ElfloaderHashNone=ON
ELFLOADER_INCLUDE_DTB: true # ElfloaderIncludeDtb=ON
ELFLOADER_ROOTSERVERS_LAST: false
ELFLOADER_ARMV8_LEAVE_AARCH64: false
ELFLOADER_PRECOMPILE: false
